// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KGV_GtWIbuDSC-8lHxeETjGGFpme3XY',
    appId: '1:566018233038:web:b0bcbd6179ec3447b5f69f',
    messagingSenderId: '566018233038',
    projectId: 'ecommerceapp-48ee2',
    authDomain: 'ecommerceapp-48ee2.firebaseapp.com',
    databaseURL: 'https://ecommerceapp-48ee2-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-48ee2.appspot.com',
    measurementId: 'G-1H4BNBH3YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAssSbPiNRweEMl6hgznQ76frcAFcPljtM',
    appId: '1:566018233038:android:d1c5d4ac54cd0332b5f69f',
    messagingSenderId: '566018233038',
    projectId: 'ecommerceapp-48ee2',
    databaseURL: 'https://ecommerceapp-48ee2-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-48ee2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjW2qLdNXKdbUzyP-6MAigZzSXSeCtDKU',
    appId: '1:566018233038:ios:47b22daf591e8e40b5f69f',
    messagingSenderId: '566018233038',
    projectId: 'ecommerceapp-48ee2',
    databaseURL: 'https://ecommerceapp-48ee2-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-48ee2.appspot.com',
    androidClientId: '566018233038-ev5mnh1lqb8738l3rqg077afqtna3h1d.apps.googleusercontent.com',
    iosClientId: '566018233038-gu2a6abf6m8in56ard3c06f4itqbkfff.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjW2qLdNXKdbUzyP-6MAigZzSXSeCtDKU',
    appId: '1:566018233038:ios:d454e7e57c1bdbffb5f69f',
    messagingSenderId: '566018233038',
    projectId: 'ecommerceapp-48ee2',
    databaseURL: 'https://ecommerceapp-48ee2-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-48ee2.appspot.com',
    androidClientId: '566018233038-ev5mnh1lqb8738l3rqg077afqtna3h1d.apps.googleusercontent.com',
    iosClientId: '566018233038-efel60a00kpop8223ca50fsr13cs5ehd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
